language: go
sudo: false
go:
  - 1.5.2
  - tip
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
  - go get -d -v -t ./...
  - go get golang.org/x/tools/cmd/vet
script:
  - go vet ./...
  - go test ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
